apiVersion: batch/v1
kind: Job
metadata:
  name: metadata
spec:
  parallelism: 1
  template:
    metadata: 
      name: metadata
    spec: 
      containers:
        - image: shonpaz123/notify
          imagePullPolicy: IfNotPresent 
          name: metadata
          args:
               ["--endpoint-url", "http://10.128.0.156:8000",
                "--access-key", "UCKKUFGSHC37GK5R8A03", 
                "--secret-key", "nKn9CkQywKhN2oJY9sp9sWlyfI4skIPoCdYkd0On",
                "--bucket", "metadata-check",
                "--kafka-endpoint", "10.128.0.159:9092", 
                "--topic", "notifications", 
                "--filter", '{"Metadata": {"FilterRules": [{"Name": "x-amz-meta-hello", "Value": "bye"}]}}']
      restartPolicy: Never
      
