apiVersion: batch/v1
kind: Job
metadata:
  name: regex
spec:
  parallelism: 1
  template:
    metadata: 
      name: regex
    spec: 
      containers:
        - image: shonpaz123/notify
          name: regex
          args:
                  ["--endpoint-url", "http://10.128.0.156:8000",
                "--access-key", "UCKKUFGSHC37GK5R8A03", 
                "--secret-key", "nKn9CkQywKhN2oJY9sp9sWlyfI4skIPoCdYkd0On",
                "--bucket", "regex",
                "--kafka-endpoint", "10.128.0.159:9092", 
                "--topic", "notifications", 
                "--filter", '{"Key": {"FilterRules": [{"Name": "regex", "Value": "hello([a-zA-Z0-9]+)"}]}}']
      restartPolicy: Never
