apiVersion: batch/v1
kind: Job
metadata:
  name: tags
spec:
  parallelism: 1
  template:
    metadata: 
      name: tags
    spec: 
      containers:
        - image: shonpaz123/notify
          imagePullPolicy: Always
          name: tags
          args:
                  ["--endpoint-url", "http://10.128.1.15:8000",
                "--access-key", "V7YD1B56TEE1DBLCOQFE", 
                "--secret-key", "LCqqa0QowS4OTl5PwVwXiwOIIf7lMwnyoXYrSDz3",
                "--bucket", "tags",
                "--kafka-endpoint", "10.128.0.159:9092", 
                "--topic", "notifications", 
                "--filter", '{"Tags": {"FilterRules": [{"Name": "color", "Value": "blue"}]}}']
      restartPolicy: Never
      
